version: '3'
services:
  database:
    container_name: database
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: event
    volumes:
      - .:/app
    working_dir: '/app'

  node:
    image: node:latest
    container_name: node
    working_dir: '/app'
    expose:
      - "3000"
    ports:
      - "${APP_PORT}:3000"
    command: bash -c "npx prisma migrate deploy && npm run build && npm run start:prod"
    volumes:
      - .:/app
    depends_on:
      - "database"